// <auto-generated />
namespace NorthwindEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Version11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version11));
        
        string IMigrationMetadata.Id
        {
            get { return "201812021411542_Version1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
